"use strict";
const $ = (id) => document.getElementById(id);
const fmt = (v, n=3) => v === null || v === undefined || !Number.isFinite(Number(v)) ? "—" : Number(v).toLocaleString(undefined,{maximumFractionDigits:n});
const when = (v) => v ? new Date(v).toLocaleString() : "—";
const text = (tag, value, cls) => {const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};
const badge = (value) => text("span", String(value || "unknown").replaceAll("_"," "), "badge "+value);
let selectedView="map", socket, mapRequest=0, captureFresh=false;
const titles={map:["Relationship map","Explore relationships that survive a separate observation window."],monitor:["Market monitor","Observe completed market moves, relationship changes and scheduled events."],health:["Data health","See which observations are fresh, complete and fit for the registered research."],experiments:["Experiments","Follow every registered hypothesis through its evidence and validation gates."]};
async function get(path){const r=await fetch(path);if(r.status===401){if(!$('login').open)$('login').showModal();throw Error("Access token required");}if(!r.ok)throw Error("The workspace API is unavailable. Saved data remains on the host.");return r.json();}
function notice(message){$('notice').textContent=message;$('notice').hidden=!message;}
function row(cells){const tr=document.createElement('tr');for(const cell of cells){const td=document.createElement('td');td.append(cell instanceof Node?cell:document.createTextNode(String(cell)));tr.append(td);}return tr;}
function empty(tbody,message,columns){tbody.replaceChildren();const tr=document.createElement('tr'),td=text('td',message,'empty');td.colSpan=columns;tr.append(td);tbody.append(tr);}
function svg(tag,attrs){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs||{}))e.setAttribute(k,v);return e;}
function selectEdge(edge){const target=$('edge-detail');target.replaceChildren(text('span',edge.kind.replaceAll('_',' ').toUpperCase(),'eyebrow'),text('h3',edge.source+' → '+edge.target));const dl=document.createElement('dl');for(const[k,v]of Object.entries({Horizon:edge.horizon,Lag:edge.lag,Status:edge.status,'First strength':fmt(edge.train.strength),'Following strength':fmt(edge.validation.strength),'First adj. p':fmt(edge.q_train,6),'Following adj. p':fmt(edge.q_validation,6),'First samples':fmt(edge.train.n,0),'Following samples':fmt(edge.validation.n,0)})){dl.append(text('dt',k),text('dd',v));}target.append(dl,text('p',edge.validation.reason||edge.train.reason||'Both windows are measured separately. This relationship does not grant permission to trade.','note'));}
function drawGraph(nodes,edges){const g=$('graph');g.replaceChildren();const positions=new Map();nodes.forEach((node,i)=>{const angle=2*Math.PI*i/Math.max(nodes.length,1)-Math.PI/2;positions.set(node.id,{x:425+300*Math.cos(angle),y:275+215*Math.sin(angle)});});const lines=[];for(const edge of edges.slice(0,150)){const a=positions.get(edge.source),b=positions.get(edge.target);if(!a||!b)continue;const line=svg('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:(edge.train.strength||0)>=0?'#70ddbd':'#e4ae6d','stroke-width':1.2,class:'edge',tabindex:0});line.addEventListener('click',()=>selectEdge(edge));line.addEventListener('keydown',e=>{if(e.key==='Enter')selectEdge(edge);});g.append(line);lines.push({line,edge});}for(const node of nodes){const p=positions.get(node.id),group=svg('g',{class:'node '+node.asset_class,transform:`translate(${p.x} ${p.y})`,tabindex:0});group.append(svg('circle',{r:9}));const label=svg('text',{x:13,y:4});label.textContent=node.id.replace('_SIP','');group.append(label);g.append(group);let dragging=false;group.addEventListener('pointerdown',e=>{dragging=true;group.setPointerCapture(e.pointerId);});group.addEventListener('pointerup',()=>dragging=false);group.addEventListener('pointermove',e=>{if(!dragging)return;const point=g.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const local=point.matrixTransform(g.getScreenCTM().inverse());p.x=Math.max(20,Math.min(790,local.x));p.y=Math.max(20,Math.min(525,local.y));group.setAttribute('transform',`translate(${p.x} ${p.y})`);for(const{line,edge}of lines){const a=positions.get(edge.source),b=positions.get(edge.target);for(const[k,v]of Object.entries({x1:a.x,y1:a.y,x2:b.x,y2:b.y}))line.setAttribute(k,v);}});} $('graph-empty').hidden=edges.length>0;}
async function loadMap(){const request=++mapRequest;const query=new URLSearchParams({horizon:$('horizon').value,kind:$('kind').value,state:$('edge-state').value});const data=await get('/api/map?'+query);if(request!==mapRequest)return;drawGraph(data.nodes,data.edges);$('edge-total').textContent=`${fmt(data.total,0)} relationships · showing ${data.edges.length}`;const tbody=$('edge-rows');tbody.replaceChildren();for(const edge of data.edges){const tr=row([edge.source,edge.target,edge.kind.replaceAll('_',' '),edge.lag,fmt(edge.train.strength),fmt(edge.validation.strength),fmt(edge.q_validation,6),badge(edge.status)]);tr.className='selectable';tr.tabIndex=0;tr.addEventListener('click',()=>selectEdge(edge));tr.addEventListener('keydown',e=>{if(e.key==='Enter')selectEdge(edge);});tbody.append(tr);}if(!data.edges.length)empty(tbody,'No relationships meet this filter. Try “All candidates” to inspect every result.',8);if(data.design)$('data-window').textContent=`Discovery only · ${data.design.start.slice(0,10)} → ${data.design.end.slice(0,10)}`;}
function sparkline(points){const chart=svg('svg',{viewBox:'0 0 300 70',role:'img','aria-label':'Recent completed prices'});if(points.length<2)return chart;const values=points.map(p=>p[1]),low=Math.min(...values),high=Math.max(...values),range=high-low||1;chart.append(svg('polyline',{fill:'none',stroke:'#70ddbd','stroke-width':1.8,points:values.map((v,i)=>`${i/(values.length-1)*298+1},${65-(v-low)/range*58}`).join(' ')}));return chart;}
function updateMonitor(data){const age=data.as_of?(Date.now()-Date.parse(data.as_of))/1000:Infinity;captureFresh=Number.isFinite(age)&&age>=-30&&age<180;$('connection').textContent=captureFresh?'Workspace connected':'Monitor capture is stale';$('connection-dot').classList.toggle('mint',captureFresh);$('monitor-time').textContent=data.as_of?'Captured '+when(data.as_of):'No capture yet';$('feed-count').textContent=captureFresh?fmt(data.healthy_feeds,0):'—';$('feed-detail').textContent=data.as_of?'Last capture '+new Date(data.as_of).toLocaleTimeString():'Waiting for a capture cycle';$('delivery-state').textContent=(data.delivery?.status||'log_only').replaceAll('_',' ');const prices=$('price-panels');prices.replaceChildren();for(const item of data.latest||[]){const card=text('article','','price-panel'),state=(data.health||[]).find(h=>h.symbol===item.symbol);card.append(text('div',item.symbol,'source'),text('strong',fmt(item.close,2)),text('p',(item.return_1m===null?'—':fmt(item.return_1m*100,3)+'%')+' · one minute'),badge(captureFresh?state?.status:'stale'),sparkline(data.history?.[item.symbol]||[]),text('small',when(item.at),'muted'));prices.append(card);}if(!prices.children.length)prices.append(text('p','No completed market observations have been captured yet.','empty'));const body=$('alert-rows');body.replaceChildren();for(const event of data.alerts||[])body.append(row([when(event.at),event.kind.replaceAll('_',' '),event.symbol,event.message,badge(event.status)]));if(!body.children.length)empty(body,'No recorded alerts. The monitor logs only observed conditions.',5);const health=$('health-rows');health.replaceChildren();for(const feed of data.health||[])health.append(row([feed.symbol,feed.source,badge(captureFresh?feed.status:'stale'),when(feed.latest_at),feed.age_seconds===undefined?'—':fmt(feed.age_seconds,0)+'s',fmt(feed.rows,0)]));if(!health.children.length)empty(health,'No feed cycle has completed.',6);}
async function loadHealth(){const data=await get('/api/health'),body=$('coverage-rows');body.replaceChildren();for(const item of data.equities){const coverage=document.createElement('span'),bar=document.createElement('progress');bar.max=1;bar.value=item.coverage;bar.setAttribute('aria-label',item.symbol+' coverage');coverage.append(bar,document.createTextNode(fmt(item.coverage*100,2)+'%'));body.append(row([item.symbol,item.feed,fmt(item.rows,0),fmt(item.missing_minutes,0),coverage,badge(item.evidence_ok?'verified':'failed')]));}if(!data.equities.length)empty(body,'Run the equity audit to populate historical coverage.',6);}
async function loadExperiments(){const data=await get('/api/experiments'),cards=$('experiment-cards');cards.replaceChildren();for(const experiment of data.cases||[]){const card=text('article','','experiment'),gate=experiment.gate||{};card.append(badge(experiment.verdict||experiment.execution),text('h3',experiment.title||experiment.case),text('p',experiment.implemented_scope||''));const results=text('div','','results');for(const[level,scenario]of Object.entries(gate.scenarios||{})){const box=document.createElement('div');box.append(text('small',level+'× COST · NET P&L'),text('strong',fmt(scenario.metrics?.net_pnl,2)));results.append(box);}card.append(results);const reasons=[...(experiment.blockers||[]),...(gate.failures||[]),...(gate.missing||[])];const ul=document.createElement('ul');for(const reason of reasons.slice(0,5))ul.append(text('li',reason));if(reasons.length>5)ul.append(text('li',`${reasons.length-5} additional recorded checks`));card.append(ul,text('small',`${experiment.registered_candidates||0} candidates · ${experiment.attempts||0} attempts · ${experiment.family||''}`));cards.append(card);}if(!cards.children.length)cards.append(text('p','No campaign report has been published yet.','empty'));}
async function refresh(){try{const data=await get('/api/summary');updateMonitor(data.monitor);$('stable-count').textContent=fmt(data.map.counts?.stable,0);$('test-count').textContent=fmt(data.map.registered_cells,0);await Promise.all([loadMap(),loadHealth(),loadExperiments()]);notice('');}catch(e){notice(e.message);$('connection').textContent='Connection unavailable';$('connection-dot').classList.remove('mint');}}
function connect(){if(socket)socket.close();socket=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws');socket.onmessage=e=>{updateMonitor(JSON.parse(e.data));};socket.onerror=()=>{$('connection').textContent='Using periodic updates';};socket.onclose=()=>{};}
for(const button of document.querySelectorAll('nav button'))button.addEventListener('click',()=>{selectedView=button.dataset.view;for(const b of document.querySelectorAll('nav button')){const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-selected',active);}for(const view of document.querySelectorAll('.view'))view.hidden=view.id!=='view-'+selectedView;[$('view-title').textContent,$('view-description').textContent]=titles[selectedView];});
for(const id of ['horizon','kind','edge-state'])$(id).addEventListener('change',()=>loadMap().catch(e=>notice(e.message)));
$('refresh').addEventListener('click',refresh);
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:$('token').value})});if(r.ok){$('token').value='';$('login').close();await refresh();connect();}else $('login-error').textContent='The token was not accepted.';});
setInterval(()=>$('clock').textContent=new Date().toLocaleTimeString(),1000);setInterval(()=>get('/api/summary').then(d=>updateMonitor(d.monitor)).catch(e=>{notice(e.message);$('connection').textContent='Connection unavailable';$('connection-dot').classList.remove('mint');}),15000);refresh().then(connect);
